import os
from Crypto.Cipher import Salsa20
from Crypto.Random import get_random_bytes


# ── helpers ───────────────────────────────────────────────────────────────────

def _save_output(content: str, filename: str = "salsa20_output.txt") -> None:
    os.makedirs("samples", exist_ok=True)
    path = os.path.join("samples", filename)
    with open(path, "w") as f:
        f.write(content)
    print(f"  [Saved] → {path}")


def _get_key() -> bytes | None:
    print("\n  Key options:")
    print("  1. Auto-generate 256-bit key (32 bytes)")
    print("  2. Enter key manually (hex)")
    choice = input("  Choice: ").strip()

    if choice == "1":
        key = get_random_bytes(32)
        print(f"  Generated Key (hex): {key.hex()}")
        return key
    elif choice == "2":
        raw = input("  Enter key (32 or 64 hex chars → 16 or 32 bytes): ").strip()
        try:
            key = bytes.fromhex(raw)
            if len(key) not in (16, 32):
                print("  [Error] Salsa20 key must be 16 or 32 bytes.")
                return None
            return key
        except ValueError:
            print("  [Error] Invalid hex string.")
            return None
    else:
        print("  [Error] Invalid choice.")
        return None


# ── core functions ────────────────────────────────────────────────────────────

def generate_key() -> None:
    print("\n--- Salsa20 Key Generation (256-bit / 32 bytes) ---")
    key = get_random_bytes(32)
    nonce = get_random_bytes(8)
    hex_key = key.hex()
    hex_nonce = nonce.hex()
    print(f"  Key   (hex): {hex_key}")
    print(f"  Nonce (hex): {hex_nonce}  ← 8 bytes, store alongside key")
    save = input("\n  Save key to file? (y/n): ").strip().lower()
    if save == "y":
        _save_output(
            f"Salsa20 Key (256-bit):\n{hex_key}\nSample Nonce:\n{hex_nonce}\n",
            "salsa20_key.txt"
        )


def encrypt_message() -> None:
    print("\n--- Salsa20 Encryption ---")
    print("  Salsa20 is a stream cipher — encryption and decryption are identical.\n")
    key = _get_key()
    if key is None:
        return

    plaintext = input("  Enter message to encrypt: ").strip()
    if not plaintext:
        print("  [Error] Message cannot be empty.")
        return

    try:
        cipher = Salsa20.new(key=key)
        nonce = cipher.nonce
        ciphertext = cipher.encrypt(plaintext.encode())

        hex_nonce = nonce.hex()
        hex_cipher = ciphertext.hex()

        print(f"\n  Nonce      (hex): {hex_nonce}  ← 8 bytes")
        print(f"  Ciphertext (hex): {hex_cipher}")

        save = input("\n  Save output to file? (y/n): ").strip().lower()
        if save == "y":
            output = (
                f"Salsa20 Encryption Output\n"
                f"Key       : {key.hex()}\n"
                f"Nonce     : {hex_nonce}\n"
                f"Ciphertext: {hex_cipher}\n"
            )
            _save_output(output)
    except Exception as e:
        print(f"  [Error] Encryption failed: {e}")


def decrypt_message() -> None:
    print("\n--- Salsa20 Decryption ---")
    print("  Salsa20 decryption = re-encrypt with same key and nonce.\n")
    key = _get_key()
    if key is None:
        return

    try:
        hex_nonce = input("  Enter Nonce (hex, 16 hex chars = 8 bytes): ").strip()
        hex_cipher = input("  Enter Ciphertext (hex): ").strip()
        nonce = bytes.fromhex(hex_nonce)
        ciphertext = bytes.fromhex(hex_cipher)

        if len(nonce) != 8:
            print("  [Error] Salsa20 nonce must be exactly 8 bytes (16 hex chars).")
            return

        cipher = Salsa20.new(key=key, nonce=nonce)
        plaintext = cipher.decrypt(ciphertext)
        print(f"\n  Decrypted Message: {plaintext.decode()}")
    except ValueError as e:
        print(f"  [Error] Invalid input: {e}")
    except UnicodeDecodeError:
        print("  [Error] Decrypted bytes are not valid UTF-8. Wrong key or nonce?")
    except Exception as e:
        print(f"  [Error] Decryption failed: {e}")


def show_how_salsa20_works() -> None:
    print("\n--- How Salsa20 Works ---")
    print("""
  Salsa20 is a stream cipher designed by Daniel J. Bernstein (2005).
  It is based on a 512-bit (64-byte) block function using 20 rounds
  of ARX operations (Add, Rotate, XOR).

  Core state (16 x 32-bit words):
    "expa"  K0    K1    K2
     K3    "nd 3"  N0    N1
     Pos   Pos   "2-by"  K4
     K5    K6    K7   "te k"

  Where:
    K  = 256-bit key (8 words)
    N  = 64-bit nonce (2 words)
    Pos= 64-bit block counter (2 words)

  Each 512-bit block is generated by 20 rounds of quarter-round mixing,
  then XORed with the initial state. The output is XORed with plaintext.

  Key Properties:
    ✅ Fast in software — no hardware acceleration needed
    ✅ 64-bit nonce + 64-bit counter = up to 2^70 bytes per key/nonce
    ✅ Designed to resist timing attacks (no data-dependent branching)
    ✅ eSTREAM portfolio winner (Profile 1 — software)
    ⚠ No built-in authentication — combine with Poly1305 if needed
    ⚠ Nonce must not be reused with same key
    """)


# ── menu ──────────────────────────────────────────────────────────────────────

def salsa20_menu() -> None:
    while True:
        print("\n--- Salsa20 ---")
        print("  Type   : Stream Cipher (ARX-based)")
        print("  Key    : 128-bit or 256-bit (default 256-bit)")
        print("  Nonce  : 64-bit (8 bytes)")
        print("  Rounds : 20")
        print("  Author : D.J. Bernstein (2005)")
        print()
        print("  1. Generate Key")
        print("  2. Encrypt Message")
        print("  3. Decrypt Message")
        print("  4. How Salsa20 Works")
        print("  5. Back")

        choice = input("\n  Select option: ").strip()

        if choice == "1":
            generate_key()
        elif choice == "2":
            encrypt_message()
        elif choice == "3":
            decrypt_message()
        elif choice == "4":
            show_how_salsa20_works()
        elif choice == "5":
            break
        else:
            print("  [Error] Invalid option. Please choose 1–5.")